[package]
name = "hackrf-sys"
version = "0.1.0"
authors = ["Michael Chesser"]

links = "hackrf"
build = "build.rs"

[build-dependencies]
gcc = "0.3"
pkg-config = { git = "https://github.com/alexcrichton/pkg-config-rs" }
